version: 2
jobs:
  test-linux:
    docker:
      - image: antoniogamiz/documentable
    steps:
      - checkout
      - run:
          name: Test documentable
          command: |
            LATEST_COMMIT=$(git rev-parse HEAD)
            FOLDER1_COMMIT=$(git log -1 --format=format:%H --full-diff doc/)
            if [ $FOLDER1_COMMIT = $LATEST_COMMIT ];
            then
                echo "Docs changed, attempting build"
                documentable start -a -v
            else
                echo "Actual docs unchanged, won't test build"
            fi

      - store_artifacts:
          path: html/

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-linux
